# Generated by Django 3.2.15 on 2024-11-14 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipe.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='method',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
