# Generated by Django 3.2.15 on 2024-11-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20241114_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(default=-1, to='recipe.Ingredient'),
        ),
    ]
