# Generated by Django 5.0.6 on 2024-07-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipe_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_ingredients',
        ),
    ]
