# Generated by Django 3.2.15 on 2024-09-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0002_mealplan_friday_mealplan_monday_mealplan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
